apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: post
  name: post
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: post
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: post
    spec:
      containers:
      - env:
        - name: DB_DSN
          value: mysql:host=remotemysql.com;dbname=N9B54G8Bry
        - name: DB_PASSWORD
          value: vUQpRxWJpF
        - name: DB_USERNAME
          value: N9B54G8Bry
        image: postor/yii2-k8s-example
        imagePullPolicy: ""
        name: post
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
